// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAltbDa4wzR-rLz10gJuVJu56pWIUku_A',
    appId: '1:442145333511:web:228cc3174f9e73d2ab25a2',
    messagingSenderId: '442145333511',
    projectId: 'registration-3ab8c',
    authDomain: 'registration-3ab8c.firebaseapp.com',
    storageBucket: 'registration-3ab8c.firebasestorage.app',
    measurementId: 'G-5K74QB57BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuBYaZQ5QqJpnt3XoF6CXTEVE5GB71F4',
    appId: '1:442145333511:android:f18235c545d2598dab25a2',
    messagingSenderId: '442145333511',
    projectId: 'registration-3ab8c',
    storageBucket: 'registration-3ab8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4k7bnbAEw3CoJGwapxFEpJUM29XuSxl8',
    appId: '1:442145333511:ios:3f98850fc8774fdeab25a2',
    messagingSenderId: '442145333511',
    projectId: 'registration-3ab8c',
    storageBucket: 'registration-3ab8c.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4k7bnbAEw3CoJGwapxFEpJUM29XuSxl8',
    appId: '1:442145333511:ios:3f98850fc8774fdeab25a2',
    messagingSenderId: '442145333511',
    projectId: 'registration-3ab8c',
    storageBucket: 'registration-3ab8c.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAltbDa4wzR-rLz10gJuVJu56pWIUku_A',
    appId: '1:442145333511:web:a8dd4002c5742395ab25a2',
    messagingSenderId: '442145333511',
    projectId: 'registration-3ab8c',
    authDomain: 'registration-3ab8c.firebaseapp.com',
    storageBucket: 'registration-3ab8c.firebasestorage.app',
    measurementId: 'G-DB67NGZH3J',
  );
}
